d_assumption(3991).
goal(1974).
asset(1974).
actor(1989).
hardware(1989).
asset(1989).
has(1989,1974).
has(1989,2949).
has(1989,2951).
has(1989,3050).
has(1989,3059).

goal(1998).
asset(1998).
goal(2003).
asset(2003).
goal(2004).
asset(2004).
goal(2633).
asset(2633).
goal(2636).
asset(2636).
actor(2671).
hardware(2671).
asset(2671).
has(2671,2003).
has(2671,2004).
has(2671,2672).
has(2671,2673).
has(2671,2686).
has(2671,2689).
has(2671,2692).
has(2671,2755).
has(2671,2756).
has(2671,2768).
has(2671,2774).
has(2671,2826).
has(2671,2842).
has(2671,2844).
has(2671,3017).
has(2671,3018).
has(2671,3021).
has(2671,3053).
has(2671,3054).
has(2671,3078).
has(2671,3134).
has(2671,3153).
has(2671,3156).
has(2671,3159).
has(2671,3174).
has(2671,3180).
has(2671,3181).
has(2671,3183).
has(2671,3190).
has(2671,3235).
has(2671,3236).
has(2671,3237).
has(2671,3461).
has(2671,3462).
has(2671,3463).
has(2671,3464).
has(2671,3465).
has(2671,3480).
has(2671,3481).
has(2671,3482).
has(2671,3483).
has(2671,3494).
has(2671,3499).
has(2671,3501).
has(2671,3504).
has(2671,4002).

goal(2672).
asset(2672).
goal(2673).
asset(2673).
goal(2683).
asset(2683).
goal(2684).
asset(2684).
goal(2686).
asset(2686).
goal(2689).
asset(2689).
goal(2692).
asset(2692).
actor(2700).
hardware(2700).
asset(2700).
has(2700,2633).
has(2700,2636).
has(2700,2683).
has(2700,2684).
has(2700,2705).
has(2700,2706).
has(2700,2707).
has(2700,2709).
has(2700,2723).
has(2700,2724).
has(2700,2875).
has(2700,2876).
has(2700,2877).
has(2700,2889).
has(2700,2899).
has(2700,2900).
has(2700,2911).
has(2700,3104).
has(2700,3196).
has(2700,3198).
has(2700,3202).
has(2700,3207).
has(2700,3209).
has(2700,3214).
has(2700,3418).
has(2700,3420).
has(2700,3421).
has(2700,3422).
has(2700,3423).
has(2700,3429).
has(2700,3431).
has(2700,3432).
has(2700,3433).
has(2700,3434).
has(2700,3511).
has(2700,3514).
has(2700,3517).
has(2700,3528).
has(2700,3532).
has(2700,3533).
has(2700,3534).
has(2700,3550).
has(2700,4004).

goal(2705).
asset(2705).
goal(2706).
asset(2706).
goal(2707).
asset(2707).
goal(2709).
asset(2709).
goal(2723).
asset(2723).
goal(2724).
asset(2724).
actor(2733).
hardware(2733).
asset(2733).
has(2733,2956).
has(2733,2957).
has(2733,2959).
has(2733,3081).
has(2733,3082).
has(2733,3091).
has(2733,3230).
has(2733,3231).
has(2733,3555).
has(2733,3557).
has(2733,3564).

actor(2738).
hardware(2738).
asset(2738).
has(2738,1998).
has(2738,2747).
has(2738,2748).
has(2738,2969).
has(2738,2970).
has(2738,2975).
has(2738,2976).
has(2738,2977).
has(2738,2989).
has(2738,3055).
has(2738,3070).
has(2738,3074).
has(2738,3083).
has(2738,3085).

goal(2745).
asset(2745).
goal(2746).
asset(2746).
goal(2747).
asset(2747).
goal(2748).
asset(2748).
actor(2751).
hardware(2751).
asset(2751).
has(2751,2746).
has(2751,2991).
has(2751,2992).
has(2751,3065).
has(2751,3067).

actor(2753).
hardware(2753).
asset(2753).
has(2753,2745).
has(2753,2997).
has(2753,2998).
has(2753,2999).
has(2753,3056).
has(2753,3057).
has(2753,3058).

goal(2755).
asset(2755).
goal(2756).
asset(2756).
goal(2768).
asset(2768).
goal(2774).
asset(2774).
goal(2826).
asset(2826).
goal(2842).
asset(2842).
goal(2844).
asset(2844).
goal(2875).
asset(2875).
goal(2876).
asset(2876).
goal(2877).
asset(2877).
goal(2889).
asset(2889).
goal(2899).
asset(2899).
goal(2900).
asset(2900).
task(2911).
goal(2949).
asset(2949).
goal(2951).
asset(2951).
goal(2956).
asset(2956).
goal(2957).
asset(2957).
task(2959).
goal(2969).
asset(2969).
goal(2970).
asset(2970).
goal(2975).
asset(2975).
goal(2976).
asset(2976).
goal(2977).
asset(2977).
goal(2989).
asset(2989).
goal(2991).
asset(2991).
goal(2992).
asset(2992).
goal(2997).
asset(2997).
goal(2998).
asset(2998).
goal(2999).
asset(2999).
goal(3017).
asset(3017).
goal(3018).
asset(3018).
goal(3021).
asset(3021).
task(3050).
task(3053).
task(3054).
task(3055).
task(3056).
task(3057).
task(3058).
task(3059).
task(3065).
task(3067).
task(3070).
task(3074).
task(3078).
task(3081).
task(3082).
task(3083).
task(3085).
task(3091).
task(3104).
task(3134).
task(3153).
task(3156).
task(3159).
task(3174).
task(3180).
task(3181).
task(3183).
task(3190).
goal(3196).
asset(3196).
task(3198).
task(3202).
task(3207).
task(3209).
task(3214).
task(3230).
goal(3231).
asset(3231).
goal(3235).
asset(3235).
goal(3236).
asset(3236).
task(3237).
actor(3281).
hardware(3281).
asset(3281).
has(3281,3296).
has(3281,3297).
has(3281,3298).
has(3281,3300).
has(3281,3301).
has(3281,3302).
has(3281,3303).
has(3281,3304).
has(3281,3312).
has(3281,3339).
has(3281,3589).
has(3281,3345).
has(3281,3346).
has(3281,3352).
has(3281,3376).
has(3281,3392).
has(3281,3393).
has(3281,3394).
has(3281,3396).
has(3281,3397).
has(3281,3404).
has(3281,3405).
has(3281,3406).
has(3281,3593).
has(3281,3613).

goal(3296).
asset(3296).
goal(3297).
asset(3297).
goal(3298).
asset(3298).
goal(3300).
asset(3300).
goal(3301).
asset(3301).
task(3302).
task(3303).
task(3304).
task(3312).
goal(3339).
asset(3339).
goal(3589).
asset(3589).
goal(3345).
asset(3345).
goal(3346).
asset(3346).
task(3352).
task(3376).
goal(3392).
asset(3392).
goal(3393).
asset(3393).
goal(3394).
asset(3394).
task(3396).
task(3397).
goal(3404).
asset(3404).
goal(3405).
asset(3405).
task(3406).
goal(3418).
asset(3418).
goal(3420).
asset(3420).
goal(3421).
asset(3421).
task(3422).
task(3423).
goal(3429).
asset(3429).
goal(3431).
asset(3431).
goal(3432).
asset(3432).
task(3433).
task(3434).
goal(3461).
asset(3461).
goal(3462).
asset(3462).
goal(3463).
asset(3463).
task(3464).
task(3465).
goal(3480).
asset(3480).
goal(3481).
asset(3481).
goal(3482).
asset(3482).
goal(3483).
asset(3483).
task(3494).
goal(3499).
asset(3499).
task(3501).
task(3511).
task(3514).
task(3517).
task(3528).
task(3532).
task(3533).
task(3534).
task(3550).
goal(3555).
asset(3555).
goal(3557).
asset(3557).
goal(3564).
asset(3564).
task(3593).
d_assumption(3613).
task(4002).
task(4004).
sec_goal(54582).
sec_attribute(security).
asset(2671).
importance(very_high).
interval(2689).
has_properties(54582,very_high,security,2671,2689).
has(null,54582).

sec_goal(54584).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(2724).
has_properties(54584,very_high,security,2700,2724).
has(null,54584).

sec_goal(54586).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3418).
has_properties(54586,very_high,security,2700,3418).
has(null,54586).

sec_goal(54588).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3429).
has_properties(54588,very_high,security,2700,3429).
has(null,54588).

sec_goal(54602).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2689).
has_properties(54602,very_high,data_confidentiality,patient_information,2689).

sec_goal(54604).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2724).
has_properties(54604,very_high,data_confidentiality,patient_information,2724).

sec_goal(54606).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3418).
has_properties(54606,very_high,data_confidentiality,patient_information,3418).

sec_goal(54608).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3429).
has_properties(54608,very_high,data_confidentiality,patient_information,3429).

sec_goal(54610).
sec_attribute(security).
asset(2671).
importance(very_high).
interval(2689).
has_properties(54610,very_high,security,2671,2689).

sec_goal(54612).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(2724).
has_properties(54612,very_high,security,2700,2724).

sec_goal(54614).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3418).
has_properties(54614,very_high,security,2700,3418).

sec_goal(54616).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3429).
has_properties(54616,very_high,security,2700,3429).

sec_goal(54620).
sec_attribute(security).
asset(3281).
importance(very_high).
interval(3296).
has_properties(54620,very_high,security,3281,3296).

sec_goal(54622).
sec_attribute(security).
asset(3281).
importance(very_high).
interval(3339).
has_properties(54622,very_high,security,3281,3339).

sec_goal(54626).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2747).
has_properties(54626,very_high,data_confidentiality,patient_information,2747).

sec_goal(54628).
sec_attribute(security).
asset(2738).
importance(very_high).
interval(2747).
has_properties(54628,very_high,security,2738,2747).

sec_goal(54630).
sec_attribute(security).
asset(2738).
importance(very_high).
interval(2747).
has_properties(54630,very_high,security,2738,2747).

sec_goal(100000).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(2689).
has_properties(100000,very_high,data_confidentiality,patient_personal_information,2689).

sec_goal(100001).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2689).
has_properties(100001,very_high,data_confidentiality,patient_information,2689).

sec_goal(100002).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(2724).
has_properties(100002,very_high,data_confidentiality,patient_personal_information,2724).

sec_goal(100003).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2724).
has_properties(100003,very_high,data_confidentiality,patient_information,2724).

sec_goal(100004).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(2774).
has_properties(100004,very_high,data_confidentiality,patient_personal_information,2774).

sec_goal(100005).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2774).
has_properties(100005,very_high,data_confidentiality,patient_information,2774).

sec_goal(100006).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(2911).
has_properties(100006,very_high,data_confidentiality,patient_personal_information,2911).

sec_goal(100007).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(2911).
has_properties(100007,very_high,data_confidentiality,patient_information,2911).

sec_goal(100008).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3078).
has_properties(100008,very_high,data_confidentiality,patient_personal_information,3078).

sec_goal(100009).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3078).
has_properties(100009,very_high,data_confidentiality,patient_information,3078).

sec_goal(100010).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3418).
has_properties(100010,very_high,data_confidentiality,patient_personal_information,3418).

sec_goal(100011).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3418).
has_properties(100011,very_high,data_confidentiality,patient_information,3418).

sec_goal(100012).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3420).
has_properties(100012,very_high,data_confidentiality,patient_personal_information,3420).

sec_goal(100013).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3420).
has_properties(100013,very_high,data_confidentiality,patient_information,3420).

sec_goal(100014).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3421).
has_properties(100014,very_high,data_confidentiality,patient_personal_information,3421).

sec_goal(100015).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3421).
has_properties(100015,very_high,data_confidentiality,patient_information,3421).

sec_goal(100016).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3422).
has_properties(100016,very_high,data_confidentiality,patient_personal_information,3422).

sec_goal(100017).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3422).
has_properties(100017,very_high,data_confidentiality,patient_information,3422).

sec_goal(100018).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3423).
has_properties(100018,very_high,data_confidentiality,patient_personal_information,3423).

sec_goal(100019).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3423).
has_properties(100019,very_high,data_confidentiality,patient_information,3423).

sec_goal(100020).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3429).
has_properties(100020,very_high,data_confidentiality,patient_personal_information,3429).

sec_goal(100021).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3429).
has_properties(100021,very_high,data_confidentiality,patient_information,3429).

sec_goal(100022).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3431).
has_properties(100022,very_high,data_confidentiality,patient_personal_information,3431).

sec_goal(100023).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3431).
has_properties(100023,very_high,data_confidentiality,patient_information,3431).

sec_goal(100024).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3432).
has_properties(100024,very_high,data_confidentiality,patient_personal_information,3432).

sec_goal(100025).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3432).
has_properties(100025,very_high,data_confidentiality,patient_information,3432).

sec_goal(100026).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3433).
has_properties(100026,very_high,data_confidentiality,patient_personal_information,3433).

sec_goal(100027).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3433).
has_properties(100027,very_high,data_confidentiality,patient_information,3433).

sec_goal(100028).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3434).
has_properties(100028,very_high,data_confidentiality,patient_personal_information,3434).

sec_goal(100029).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3434).
has_properties(100029,very_high,data_confidentiality,patient_information,3434).

sec_goal(100030).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3514).
has_properties(100030,very_high,data_confidentiality,patient_personal_information,3514).

sec_goal(100031).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3517).
has_properties(100031,very_high,data_confidentiality,patient_personal_information,3517).

sec_goal(100032).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3514).
has_properties(100032,very_high,data_confidentiality,patient_information,3514).

sec_goal(100033).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3517).
has_properties(100033,very_high,data_confidentiality,patient_information,3517).

sec_goal(100034).
sec_attribute(data_confidentiality).
asset(patient_personal_information).
importance(very_high).
interval(3550).
has_properties(100034,very_high,data_confidentiality,patient_personal_information,3550).

sec_goal(100035).
sec_attribute(data_confidentiality).
asset(patient_information).
importance(very_high).
interval(3550).
has_properties(100035,very_high,data_confidentiality,patient_information,3550).

sec_goal(100036).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(2689).
has_properties(100036,very_high,data_confidentiality,patient_insurance_information,2689).

sec_goal(100037).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(2724).
has_properties(100037,very_high,data_confidentiality,patient_insurance_information,2724).

sec_goal(100038).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(2774).
has_properties(100038,very_high,data_confidentiality,patient_insurance_information,2774).

sec_goal(100039).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(2911).
has_properties(100039,very_high,data_confidentiality,patient_insurance_information,2911).

sec_goal(100040).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3078).
has_properties(100040,very_high,data_confidentiality,patient_insurance_information,3078).

sec_goal(100041).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3418).
has_properties(100041,very_high,data_confidentiality,patient_insurance_information,3418).

sec_goal(100042).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3420).
has_properties(100042,very_high,data_confidentiality,patient_insurance_information,3420).

sec_goal(100043).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3421).
has_properties(100043,very_high,data_confidentiality,patient_insurance_information,3421).

sec_goal(100044).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3422).
has_properties(100044,very_high,data_confidentiality,patient_insurance_information,3422).

sec_goal(100045).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3423).
has_properties(100045,very_high,data_confidentiality,patient_insurance_information,3423).

sec_goal(100046).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3429).
has_properties(100046,very_high,data_confidentiality,patient_insurance_information,3429).

sec_goal(100047).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3431).
has_properties(100047,very_high,data_confidentiality,patient_insurance_information,3431).

sec_goal(100048).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3432).
has_properties(100048,very_high,data_confidentiality,patient_insurance_information,3432).

sec_goal(100049).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3433).
has_properties(100049,very_high,data_confidentiality,patient_insurance_information,3433).

sec_goal(100050).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3434).
has_properties(100050,very_high,data_confidentiality,patient_insurance_information,3434).

sec_goal(100051).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3514).
has_properties(100051,very_high,data_confidentiality,patient_insurance_information,3514).

sec_goal(100052).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3517).
has_properties(100052,very_high,data_confidentiality,patient_insurance_information,3517).

sec_goal(100053).
sec_attribute(data_confidentiality).
asset(patient_insurance_information).
importance(very_high).
interval(3550).
has_properties(100053,very_high,data_confidentiality,patient_insurance_information,3550).

sec_goal(100054).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(2689).
has_properties(100054,very_high,data_confidentiality,patient_activities_data,2689).

sec_goal(100055).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(2724).
has_properties(100055,very_high,data_confidentiality,patient_activities_data,2724).

sec_goal(100056).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(2774).
has_properties(100056,very_high,data_confidentiality,patient_activities_data,2774).

sec_goal(100057).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(2911).
has_properties(100057,very_high,data_confidentiality,patient_activities_data,2911).

sec_goal(100058).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3078).
has_properties(100058,very_high,data_confidentiality,patient_activities_data,3078).

sec_goal(100059).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3418).
has_properties(100059,very_high,data_confidentiality,patient_activities_data,3418).

sec_goal(100060).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3420).
has_properties(100060,very_high,data_confidentiality,patient_activities_data,3420).

sec_goal(100061).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3421).
has_properties(100061,very_high,data_confidentiality,patient_activities_data,3421).

sec_goal(100062).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3422).
has_properties(100062,very_high,data_confidentiality,patient_activities_data,3422).

sec_goal(100063).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3423).
has_properties(100063,very_high,data_confidentiality,patient_activities_data,3423).

sec_goal(100064).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3429).
has_properties(100064,very_high,data_confidentiality,patient_activities_data,3429).

sec_goal(100065).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3431).
has_properties(100065,very_high,data_confidentiality,patient_activities_data,3431).

sec_goal(100066).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3432).
has_properties(100066,very_high,data_confidentiality,patient_activities_data,3432).

sec_goal(100067).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3433).
has_properties(100067,very_high,data_confidentiality,patient_activities_data,3433).

sec_goal(100068).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3434).
has_properties(100068,very_high,data_confidentiality,patient_activities_data,3434).

sec_goal(100069).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3514).
has_properties(100069,very_high,data_confidentiality,patient_activities_data,3514).

sec_goal(100070).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3517).
has_properties(100070,very_high,data_confidentiality,patient_activities_data,3517).

sec_goal(100071).
sec_attribute(data_confidentiality).
asset(patient_activities_data).
importance(very_high).
interval(3550).
has_properties(100071,very_high,data_confidentiality,patient_activities_data,3550).

sec_goal(100072).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(2689).
has_properties(100072,very_high,data_confidentiality,patient_medical_data,2689).

sec_goal(100073).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(2724).
has_properties(100073,very_high,data_confidentiality,patient_medical_data,2724).

sec_goal(100074).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(2774).
has_properties(100074,very_high,data_confidentiality,patient_medical_data,2774).

sec_goal(100075).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(2911).
has_properties(100075,very_high,data_confidentiality,patient_medical_data,2911).

sec_goal(100076).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3078).
has_properties(100076,very_high,data_confidentiality,patient_medical_data,3078).

sec_goal(100077).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3418).
has_properties(100077,very_high,data_confidentiality,patient_medical_data,3418).

sec_goal(100078).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3420).
has_properties(100078,very_high,data_confidentiality,patient_medical_data,3420).

sec_goal(100079).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3421).
has_properties(100079,very_high,data_confidentiality,patient_medical_data,3421).

sec_goal(100080).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3422).
has_properties(100080,very_high,data_confidentiality,patient_medical_data,3422).

sec_goal(100081).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3423).
has_properties(100081,very_high,data_confidentiality,patient_medical_data,3423).

sec_goal(100082).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3429).
has_properties(100082,very_high,data_confidentiality,patient_medical_data,3429).

sec_goal(100083).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3431).
has_properties(100083,very_high,data_confidentiality,patient_medical_data,3431).

sec_goal(100084).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3432).
has_properties(100084,very_high,data_confidentiality,patient_medical_data,3432).

sec_goal(100085).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3433).
has_properties(100085,very_high,data_confidentiality,patient_medical_data,3433).

sec_goal(100086).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3434).
has_properties(100086,very_high,data_confidentiality,patient_medical_data,3434).

sec_goal(100087).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3514).
has_properties(100087,very_high,data_confidentiality,patient_medical_data,3514).

sec_goal(100088).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3517).
has_properties(100088,very_high,data_confidentiality,patient_medical_data,3517).

sec_goal(100089).
sec_attribute(data_confidentiality).
asset(patient_medical_data).
importance(very_high).
interval(3550).
has_properties(100089,very_high,data_confidentiality,patient_medical_data,3550).

sec_goal(100090).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(2689).
has_properties(100090,very_high,data_confidentiality,patient_login_credentials,2689).

sec_goal(100091).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(2724).
has_properties(100091,very_high,data_confidentiality,patient_login_credentials,2724).

sec_goal(100092).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(2774).
has_properties(100092,very_high,data_confidentiality,patient_login_credentials,2774).

sec_goal(100093).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(2911).
has_properties(100093,very_high,data_confidentiality,patient_login_credentials,2911).

sec_goal(100094).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3078).
has_properties(100094,very_high,data_confidentiality,patient_login_credentials,3078).

sec_goal(100095).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3418).
has_properties(100095,very_high,data_confidentiality,patient_login_credentials,3418).

sec_goal(100096).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3420).
has_properties(100096,very_high,data_confidentiality,patient_login_credentials,3420).

sec_goal(100097).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3421).
has_properties(100097,very_high,data_confidentiality,patient_login_credentials,3421).

sec_goal(100098).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3422).
has_properties(100098,very_high,data_confidentiality,patient_login_credentials,3422).

sec_goal(100099).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3423).
has_properties(100099,very_high,data_confidentiality,patient_login_credentials,3423).

sec_goal(100100).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3429).
has_properties(100100,very_high,data_confidentiality,patient_login_credentials,3429).

sec_goal(100101).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3431).
has_properties(100101,very_high,data_confidentiality,patient_login_credentials,3431).

sec_goal(100102).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3432).
has_properties(100102,very_high,data_confidentiality,patient_login_credentials,3432).

sec_goal(100103).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3433).
has_properties(100103,very_high,data_confidentiality,patient_login_credentials,3433).

sec_goal(100104).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3434).
has_properties(100104,very_high,data_confidentiality,patient_login_credentials,3434).

sec_goal(100105).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3514).
has_properties(100105,very_high,data_confidentiality,patient_login_credentials,3514).

sec_goal(100106).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3517).
has_properties(100106,very_high,data_confidentiality,patient_login_credentials,3517).

sec_goal(100107).
sec_attribute(data_confidentiality).
asset(patient_login_credentials).
importance(very_high).
interval(3550).
has_properties(100107,very_high,data_confidentiality,patient_login_credentials,3550).

sec_goal(100108).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(2689).
has_properties(100108,very_high,data_confidentiality,patient_billing_information,2689).

sec_goal(100109).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(2724).
has_properties(100109,very_high,data_confidentiality,patient_billing_information,2724).

sec_goal(100110).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(2774).
has_properties(100110,very_high,data_confidentiality,patient_billing_information,2774).

sec_goal(100111).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(2911).
has_properties(100111,very_high,data_confidentiality,patient_billing_information,2911).

sec_goal(100112).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3078).
has_properties(100112,very_high,data_confidentiality,patient_billing_information,3078).

sec_goal(100113).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3418).
has_properties(100113,very_high,data_confidentiality,patient_billing_information,3418).

sec_goal(100114).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3420).
has_properties(100114,very_high,data_confidentiality,patient_billing_information,3420).

sec_goal(100115).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3421).
has_properties(100115,very_high,data_confidentiality,patient_billing_information,3421).

sec_goal(100116).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3422).
has_properties(100116,very_high,data_confidentiality,patient_billing_information,3422).

sec_goal(100117).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3423).
has_properties(100117,very_high,data_confidentiality,patient_billing_information,3423).

sec_goal(100118).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3429).
has_properties(100118,very_high,data_confidentiality,patient_billing_information,3429).

sec_goal(100119).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3431).
has_properties(100119,very_high,data_confidentiality,patient_billing_information,3431).

sec_goal(100120).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3432).
has_properties(100120,very_high,data_confidentiality,patient_billing_information,3432).

sec_goal(100121).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3433).
has_properties(100121,very_high,data_confidentiality,patient_billing_information,3433).

sec_goal(100122).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3434).
has_properties(100122,very_high,data_confidentiality,patient_billing_information,3434).

sec_goal(100123).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3514).
has_properties(100123,very_high,data_confidentiality,patient_billing_information,3514).

sec_goal(100124).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3517).
has_properties(100124,very_high,data_confidentiality,patient_billing_information,3517).

sec_goal(100125).
sec_attribute(data_confidentiality).
asset(patient_billing_information).
importance(very_high).
interval(3550).
has_properties(100125,very_high,data_confidentiality,patient_billing_information,3550).

sec_goal(100126).
sec_attribute(data_confidentiality).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100126,very_high,data_confidentiality,2671,2689).

sec_goal(100127).
sec_attribute(confidentiality).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100127,very_high,confidentiality,2671,2689).

sec_goal(100128).
sec_attribute(data_confidentiality).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100128,very_high,data_confidentiality,2671,2774).

sec_goal(100129).
sec_attribute(confidentiality).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100129,very_high,confidentiality,2671,2774).

sec_goal(100130).
sec_attribute(data_confidentiality).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100130,very_high,data_confidentiality,2671,3078).

sec_goal(100131).
sec_attribute(confidentiality).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100131,very_high,confidentiality,2671,3078).

sec_goal(100132).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100132,very_high,data_confidentiality,2700,2724).

sec_goal(100133).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100133,very_high,confidentiality,2700,2724).

sec_goal(100134).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100134,very_high,data_confidentiality,2700,2911).

sec_goal(100135).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100135,very_high,confidentiality,2700,2911).

sec_goal(100136).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100136,very_high,data_confidentiality,2700,3418).

sec_goal(100137).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100137,very_high,confidentiality,2700,3418).

sec_goal(100138).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100138,very_high,data_confidentiality,2700,3420).

sec_goal(100139).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100139,very_high,confidentiality,2700,3420).

sec_goal(100140).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100140,very_high,data_confidentiality,2700,3421).

sec_goal(100141).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100141,very_high,confidentiality,2700,3421).

sec_goal(100142).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100142,very_high,data_confidentiality,2700,3422).

sec_goal(100143).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100143,very_high,confidentiality,2700,3422).

sec_goal(100144).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100144,very_high,data_confidentiality,2700,3423).

sec_goal(100145).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100145,very_high,confidentiality,2700,3423).

sec_goal(100146).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100146,very_high,data_confidentiality,2700,3429).

sec_goal(100147).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100147,very_high,confidentiality,2700,3429).

sec_goal(100148).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100148,very_high,data_confidentiality,2700,3431).

sec_goal(100149).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100149,very_high,confidentiality,2700,3431).

sec_goal(100150).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100150,very_high,data_confidentiality,2700,3432).

sec_goal(100151).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100151,very_high,confidentiality,2700,3432).

sec_goal(100152).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100152,very_high,data_confidentiality,2700,3433).

sec_goal(100153).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100153,very_high,confidentiality,2700,3433).

sec_goal(100154).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100154,very_high,data_confidentiality,2700,3434).

sec_goal(100155).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100155,very_high,confidentiality,2700,3434).

sec_goal(100156).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100156,very_high,data_confidentiality,2700,3514).

sec_goal(100157).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100157,very_high,data_confidentiality,2700,3517).

sec_goal(100158).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100158,very_high,confidentiality,2700,3514).

sec_goal(100159).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100159,very_high,confidentiality,2700,3517).

sec_goal(100160).
sec_attribute(data_confidentiality).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100160,very_high,data_confidentiality,2700,3550).

sec_goal(100161).
sec_attribute(confidentiality).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100161,very_high,confidentiality,2700,3550).

sec_goal(100162).
sec_attribute(security).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100162,very_high,security,2671,2774).

sec_goal(100163).
sec_attribute(security).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100163,very_high,security,2671,2689).

sec_goal(100164).
sec_attribute(security).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100164,very_high,security,2671,3078).

sec_goal(100165).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100165,very_high,security,2700,2911).

sec_goal(100166).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100166,very_high,security,2700,2724).

sec_goal(100167).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100167,very_high,security,2700,3420).

sec_goal(100168).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100168,very_high,security,2700,3418).

sec_goal(100169).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100169,very_high,security,2700,3421).

sec_goal(100170).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100170,very_high,security,2700,3422).

sec_goal(100171).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100171,very_high,security,2700,3423).

sec_goal(100172).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100172,very_high,security,2700,3431).

sec_goal(100173).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100173,very_high,security,2700,3429).

sec_goal(100174).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100174,very_high,security,2700,3432).

sec_goal(100175).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100175,very_high,security,2700,3433).

sec_goal(100176).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100176,very_high,security,2700,3434).

sec_goal(100177).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100177,very_high,security,2700,3514).

sec_goal(100178).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100178,very_high,security,2700,3517).

sec_goal(100179).
sec_attribute(security).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100179,very_high,security,2700,3550).

sec_goal(100180).
sec_attribute(integrity).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100180,very_high,integrity,2671,2689).

sec_goal(100181).
sec_attribute(integrity).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100181,very_high,integrity,2671,2774).

sec_goal(100182).
sec_attribute(integrity).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100182,very_high,integrity,2671,3078).

sec_goal(100183).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100183,very_high,integrity,2700,2724).

sec_goal(100184).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100184,very_high,integrity,2700,2911).

sec_goal(100185).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100185,very_high,integrity,2700,3418).

sec_goal(100186).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100186,very_high,integrity,2700,3420).

sec_goal(100187).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100187,very_high,integrity,2700,3421).

sec_goal(100188).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100188,very_high,integrity,2700,3422).

sec_goal(100189).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100189,very_high,integrity,2700,3423).

sec_goal(100190).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100190,very_high,integrity,2700,3429).

sec_goal(100191).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100191,very_high,integrity,2700,3431).

sec_goal(100192).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100192,very_high,integrity,2700,3432).

sec_goal(100193).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100193,very_high,integrity,2700,3433).

sec_goal(100194).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100194,very_high,integrity,2700,3434).

sec_goal(100195).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100195,very_high,integrity,2700,3514).

sec_goal(100196).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100196,very_high,integrity,2700,3517).

sec_goal(100197).
sec_attribute(integrity).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100197,very_high,integrity,2700,3550).

sec_goal(100198).
sec_attribute(availability).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100198,very_high,availability,2671,2689).

sec_goal(100199).
sec_attribute(availability).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100199,very_high,availability,2671,2774).

sec_goal(100200).
sec_attribute(availability).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100200,very_high,availability,2671,3078).

sec_goal(100201).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100201,very_high,availability,2700,2724).

sec_goal(100202).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100202,very_high,availability,2700,2911).

sec_goal(100203).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100203,very_high,availability,2700,3418).

sec_goal(100204).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100204,very_high,availability,2700,3420).

sec_goal(100205).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100205,very_high,availability,2700,3421).

sec_goal(100206).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100206,very_high,availability,2700,3422).

sec_goal(100207).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100207,very_high,availability,2700,3423).

sec_goal(100208).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100208,very_high,availability,2700,3429).

sec_goal(100209).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100209,very_high,availability,2700,3431).

sec_goal(100210).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100210,very_high,availability,2700,3432).

sec_goal(100211).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100211,very_high,availability,2700,3433).

sec_goal(100212).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100212,very_high,availability,2700,3434).

sec_goal(100213).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100213,very_high,availability,2700,3514).

sec_goal(100214).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100214,very_high,availability,2700,3517).

sec_goal(100215).
sec_attribute(availability).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100215,very_high,availability,2700,3550).

sec_goal(100216).
sec_attribute(data_integrity).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100216,very_high,data_integrity,2671,2689).

sec_goal(100217).
sec_attribute(data_integrity).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100217,very_high,data_integrity,2671,2774).

sec_goal(100218).
sec_attribute(data_integrity).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100218,very_high,data_integrity,2671,3078).

sec_goal(100219).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100219,very_high,data_integrity,2700,2724).

sec_goal(100220).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100220,very_high,data_integrity,2700,2911).

sec_goal(100221).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100221,very_high,data_integrity,2700,3418).

sec_goal(100222).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100222,very_high,data_integrity,2700,3420).

sec_goal(100223).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100223,very_high,data_integrity,2700,3421).

sec_goal(100224).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100224,very_high,data_integrity,2700,3422).

sec_goal(100225).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100225,very_high,data_integrity,2700,3423).

sec_goal(100226).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100226,very_high,data_integrity,2700,3429).

sec_goal(100227).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100227,very_high,data_integrity,2700,3431).

sec_goal(100228).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100228,very_high,data_integrity,2700,3432).

sec_goal(100229).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100229,very_high,data_integrity,2700,3433).

sec_goal(100230).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100230,very_high,data_integrity,2700,3434).

sec_goal(100231).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100231,very_high,data_integrity,2700,3514).

sec_goal(100232).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100232,very_high,data_integrity,2700,3517).

sec_goal(100233).
sec_attribute(data_integrity).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100233,very_high,data_integrity,2700,3550).

sec_goal(100234).
sec_attribute(data_availability).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100234,very_high,data_availability,2671,2689).

sec_goal(100235).
sec_attribute(data_availability).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100235,very_high,data_availability,2671,2774).

sec_goal(100236).
sec_attribute(data_availability).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100236,very_high,data_availability,2671,3078).

sec_goal(100237).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100237,very_high,data_availability,2700,2724).

sec_goal(100238).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100238,very_high,data_availability,2700,2911).

sec_goal(100239).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100239,very_high,data_availability,2700,3418).

sec_goal(100240).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100240,very_high,data_availability,2700,3420).

sec_goal(100241).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100241,very_high,data_availability,2700,3421).

sec_goal(100242).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100242,very_high,data_availability,2700,3422).

sec_goal(100243).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100243,very_high,data_availability,2700,3423).

sec_goal(100244).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100244,very_high,data_availability,2700,3429).

sec_goal(100245).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100245,very_high,data_availability,2700,3431).

sec_goal(100246).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100246,very_high,data_availability,2700,3432).

sec_goal(100247).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100247,very_high,data_availability,2700,3433).

sec_goal(100248).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100248,very_high,data_availability,2700,3434).

sec_goal(100249).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100249,very_high,data_availability,2700,3514).

sec_goal(100250).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100250,very_high,data_availability,2700,3517).

sec_goal(100251).
sec_attribute(data_availability).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100251,very_high,data_availability,2700,3550).

sec_goal(100252).
sec_attribute(hardware_integrity).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100252,very_high,hardware_integrity,2671,2689).

sec_goal(100253).
sec_attribute(hardware_integrity).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100253,very_high,hardware_integrity,2671,2774).

sec_goal(100254).
sec_attribute(hardware_integrity).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100254,very_high,hardware_integrity,2671,3078).

sec_goal(100255).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100255,very_high,hardware_integrity,2700,2724).

sec_goal(100256).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100256,very_high,hardware_integrity,2700,2911).

sec_goal(100257).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100257,very_high,hardware_integrity,2700,3418).

sec_goal(100258).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100258,very_high,hardware_integrity,2700,3420).

sec_goal(100259).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100259,very_high,hardware_integrity,2700,3421).

sec_goal(100260).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100260,very_high,hardware_integrity,2700,3422).

sec_goal(100261).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100261,very_high,hardware_integrity,2700,3423).

sec_goal(100262).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100262,very_high,hardware_integrity,2700,3429).

sec_goal(100263).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100263,very_high,hardware_integrity,2700,3431).

sec_goal(100264).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100264,very_high,hardware_integrity,2700,3432).

sec_goal(100265).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100265,very_high,hardware_integrity,2700,3433).

sec_goal(100266).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100266,very_high,hardware_integrity,2700,3434).

sec_goal(100267).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100267,very_high,hardware_integrity,2700,3514).

sec_goal(100268).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100268,very_high,hardware_integrity,2700,3517).

sec_goal(100269).
sec_attribute(hardware_integrity).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100269,very_high,hardware_integrity,2700,3550).

sec_goal(100270).
sec_attribute(hardware_availability).
asset(2671).
importance(very_high).
interval(2689).
has_properties(100270,very_high,hardware_availability,2671,2689).

sec_goal(100271).
sec_attribute(hardware_availability).
asset(2671).
importance(very_high).
interval(2774).
has_properties(100271,very_high,hardware_availability,2671,2774).

sec_goal(100272).
sec_attribute(hardware_availability).
asset(2671).
importance(very_high).
interval(3078).
has_properties(100272,very_high,hardware_availability,2671,3078).

sec_goal(100273).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(2724).
has_properties(100273,very_high,hardware_availability,2700,2724).

sec_goal(100274).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(2911).
has_properties(100274,very_high,hardware_availability,2700,2911).

sec_goal(100275).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3418).
has_properties(100275,very_high,hardware_availability,2700,3418).

sec_goal(100276).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3420).
has_properties(100276,very_high,hardware_availability,2700,3420).

sec_goal(100277).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3421).
has_properties(100277,very_high,hardware_availability,2700,3421).

sec_goal(100278).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3422).
has_properties(100278,very_high,hardware_availability,2700,3422).

sec_goal(100279).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3423).
has_properties(100279,very_high,hardware_availability,2700,3423).

sec_goal(100280).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3429).
has_properties(100280,very_high,hardware_availability,2700,3429).

sec_goal(100281).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3431).
has_properties(100281,very_high,hardware_availability,2700,3431).

sec_goal(100282).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3432).
has_properties(100282,very_high,hardware_availability,2700,3432).

sec_goal(100283).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3433).
has_properties(100283,very_high,hardware_availability,2700,3433).

sec_goal(100284).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3434).
has_properties(100284,very_high,hardware_availability,2700,3434).

sec_goal(100285).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3514).
has_properties(100285,very_high,hardware_availability,2700,3514).

sec_goal(100286).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3517).
has_properties(100286,very_high,hardware_availability,2700,3517).

sec_goal(100287).
sec_attribute(hardware_availability).
asset(2700).
importance(very_high).
interval(3550).
has_properties(100287,very_high,hardware_availability,2700,3550).

and_refine(2755,2672).
and_refine(2756,2672).
refine(3021,2673).
and_refine(3018,2692).
and_refine(2768,2692).
and_refine(3017,2692).
refine(2774,2689).
and_refine(2826,2686).
and_refine(2844,2003).
and_refine(2889,2684).
and_refine(2900,2636).
and_refine(2899,2636).
and_refine(2877,2683).
and_refine(2876,2683).
and_refine(2875,2683).
and_refine(2911,2705).
and_refine(2951,1974).
and_refine(2949,1974).
and_refine(2969,2748).
and_refine(2970,2748).
and_refine(2975,2747).
and_refine(2977,2747).
and_refine(2976,2747).
refine(2989,1998).
and_refine(2991,2746).
and_refine(2992,2746).
and_refine(2999,2745).
and_refine(2998,2745).
and_refine(2997,2745).
operationalize(3050,2951).
operationalize(3059,2949).
operationalize(3058,2997).
operationalize(3057,2998).
operationalize(3056,2999).
operationalize(3065,2991).
operationalize(3067,2992).
operationalize(3055,2989).
operationalize(3070,2976).
operationalize(3074,2975).
operationalize(3083,2970).
operationalize(3085,2969).
operationalize(3082,2959).
operationalize(3081,2956).
operationalize(3091,2957).
operationalize(3104,2877).
operationalize(3078,2774).
operationalize(3054,2826).
operationalize(3053,2844).
operationalize(3153,3021).
operationalize(3159,2756).
operationalize(3159,3018).
operationalize(3156,2768).
operationalize(3174,3017).
operationalize(3190,2842).
and_refine(3196,2684).
operationalize(3198,3196).
operationalize(3202,2900).
operationalize(3207,2875).
operationalize(3209,2876).
operationalize(3230,3231).
operationalize(3085,2977).
operationalize(3237,3236).
refine(3236,3235).
and_refine(3297,3296).
and_refine(3298,3296).
and_refine(3300,3296).
and_refine(3301,3296).
operationalize(3304,3297).
operationalize(3302,3300).
operationalize(3312,3301).
operationalize(3303,3298).
and_refine(3345,3339).
and_refine(3589,3339).
and_refine(3346,3339).
operationalize(3376,3346).
operationalize(3352,3345).
and_refine(3393,3392).
and_refine(3394,3392).
operationalize(3396,3394).
operationalize(3397,3393).
refine(3405,3404).
operationalize(3406,3405).
and_refine(3420,3418).
and_refine(3421,3418).
operationalize(3423,3421).
operationalize(3422,3420).
and_refine(3432,3429).
and_refine(3431,3429).
operationalize(3433,3432).
operationalize(3434,3431).
and_refine(3462,3461).
and_refine(3463,3461).
operationalize(3464,3462).
operationalize(3465,3463).
and_refine(3480,2004).
and_refine(3482,2004).
and_refine(3481,2004).
and_refine(3483,2004).
operationalize(3134,3480).
operationalize(3180,3481).
operationalize(3181,3482).
operationalize(3183,3483).
and_refine(3494,3461).
and_refine(2842,2003).
and_refine(3499,2003).
operationalize(3501,3499).
and_refine(2774,2686).
depend(4004,2844,3504).
operationalize(3511,2633).
operationalize(3514,3517).
and_refine(3517,3429).
depend(3528,2003,2023).
and_refine(3214,2709).
and_refine(3528,2709).
and_refine(3532,2707).
and_refine(2911,2707).
and_refine(2911,2706).
and_refine(3533,2706).
and_refine(3534,2705).
and_refine(2911,2724).
and_refine(3550,2724).
refine(2957,3555).
refine(2956,3557).
refine(2959,3564).
operationalize(3593,3589).
and_refine(3613,3339).
operationalize(4002,2755).
operationalize(4004,2889).
support(2633,2386).
support(2633,2373).
support(2636,2553).
support(2633,2391).
support(2672,2339).
support(2673,2345).
support(2692,2517).
support(2689,2401).
support(2686,2427).
support(2684,2368).
support(2683,2386).
support(2709,2373).
support(2707,2391).
support(2706,2404).
support(2705,2405).
support(2724,2410).
support(3564,2263).
support(2748,2187).
support(2747,2193).
support(2746,2313).
support(2745,2484).
support(3392,2475).
support(3404,2474).
support(3296,2374).
support(3418,2459).
support(3429,2402).
support(3461,2365).
support(3339,1413).
and_refine(54602,54303).
and_refine(54604,54303).
and_refine(54606,54303).
and_refine(54608,54303).
and_refine(54610,54303).
and_refine(54612,54303).
and_refine(54614,54303).
and_refine(54616,54303).
and_refine(54620,54323).
and_refine(54622,54323).
and_refine(54626,54329).
and_refine(54628,54329).
refine(54630,54343).

